[package]
name = "reed"
version = "0.1.0"
authors = ["sidju <contact@sidju.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
debug = []

[dependencies]
regex = "1.3"
syntect = { version = "4.1", default-features = false, features = ["default-fancy"]}