[package]
name = "hired"
description = "Highlighting rust clone of ed"
version = "0.3.0"
homepage = "https://github.com/sidju/hired"
repository = "https://github.com/sidju/hired"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed", "syntax-highlighting", "cli"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2018"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.*",
]

[features]
debug = []

[dependencies]
regex = "1.4"
syntect = { version = "4.5", default-features = false, features = ["default-fancy"]}
derivative = "2.1" 
crossterm = "0.19"
