[package]
name = "hired"
description = "Highlighted rust clone of ed"
version = "0.1.2"
homepage = "https://github.com/sidju/hired"
repository = "https://github.com/sidju/hired"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed", "syntax-highlighting", "cli"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2018"

include = [
  "**/*.rs",
  "Cargo.*",
]

[features]
debug = []

[dependencies]
regex = "1.3"
syntect = { version = "4.1", default-features = false, features = ["default-fancy"]}
derivative = "2.1" 
