[package]
name = "add-ed"
description = "Embeddable pure rust editor based on ED"
version = "0.8.0"
repository = "https://github.com/sidju/add-ed"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2018"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.toml",
]

[features]
vecbuffer = ["regex"]
initial_input_data = []

[dependencies]
regex = { version = "1", optional = true }

[[bin]]
name = "classic"
required-features = ["vecbuffer"]
