[package]
name = "add-ed"
description = "Embeddable pure rust editor based on ED"
version = "0.5.0"
homepage = "https://github.com/sidju/add-ed"
repository = "https://github.com/sidju/add-ed"
readme = "README.md"
categories = ["text-editors"]
keywords = ["ed"]
authors = ["sidju <contact@sidju.se>"]
license = "MIT"
edition = "2018"

include = [
  "assets/*",
  "**/*.rs",
  "Cargo.*",
]

[features]
vecbuffer = []

[dependencies]
regex = "1.4"

[[bin]]
name = "classic"
required-features = ["vecbuffer"]
